//HintName: LambdaStartup.g.cs
// <auto-generated>
//     Generated by the Lambda.Host source generator.
// </auto-generated>

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Tests;

public class LambdaStartupService : IHostedService
{
    private readonly global::Lambda.Host.DelegateHolder _delegateHolder;
    private readonly global::System.IServiceProvider _serviceProvider;
    
    public LambdaStartupService(global::Lambda.Host.DelegateHolder delegateHolder, IServiceProvider serviceProvider)
    {
        _delegateHolder = delegateHolder;
        _serviceProvider = serviceProvider;
    }
    
    public async global::System.Threading.Tasks.Task StartAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        if (!_delegateHolder.IsHandlerSet)
            throw new InvalidOperationException("Handler is not set");
            
        if (_delegateHolder.Handler is not Func<string, global::IService, global::IService> lambdaHandler)
            throw new InvalidOperationException("Invalid handler type.");
            
        var lambdaSerializer = _serviceProvider.GetService<global::Amazon.Lambda.Core.ILambdaSerializer>() ?? new global::Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();

        await global::Amazon.Lambda.RuntimeSupport.LambdaBootstrapBuilder
            .Create(
                (string input) => 
                {
                    using var scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(_serviceProvider);
                    
                    var service = scope.ServiceProvider.GetRequiredService<global::IService>();
                    
                    var response = lambdaHandler(input, service);
                    
                    return response;
                },
                lambdaSerializer
            )
            .Build()
            .RunAsync(cancellationToken);
    }

    public global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        return global::System.Threading.Tasks.Task.CompletedTask;
    }
}