name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

autolabeler:
  - label: 'type: feat'
    title:
      - '/feat(\([^)]*\))?:/i'
  - label: 'type: fix'
    title:
      - '/fix(\([^)]*\))?:/i'
  - label: 'type: docs'
    title:
      - '/docs(\([^)]*\))?:/i'
  - label: 'type: refactor'
    title:
      - '/refactor(\([^)]*\))?:/i'
  - label: 'type: test'
    title:
      - '/test(\([^)]*\))?:/i'
  - label: 'type: chore'
    title:
      - '/chore(\([^)]*\))?:/i'
  - label: 'type: ci'
    title:
      - '/ci(\([^)]*\))?:/i'
  - label: 'breaking-change'
    body:
      - '/BREAKING CHANGE/i'

categories:
  - title: '🚀 Features'
    labels:
      - 'type: feat'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type: fix'
      - 'bug'
      - 'bugfix'
  - title: '📚 Documentation'
    labels:
      - 'type: docs'
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'type: perf'
      - 'performance'
  - title: '🔄 Refactoring'
    labels:
      - 'type: refactor'
      - 'refactor'
  - title: '✅ Tests'
    labels:
      - 'type: test'
      - 'test'
  - title: '🔧 Maintenance'
    labels:
      - 'type: chore'
      - 'type: ci'
      - 'chore'
      - 'ci'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking-change'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'breaking-change'
  minor:
    labels:
      - 'type: feat'
      - 'feature'
  patch:
    labels:
      - 'type: fix'
      - 'type: docs'
      - 'type: chore'
      - 'type: ci'
      - 'bug'
  default: patch

template: |
  ## Summary
  
  SUMMARY_GOES_HERE
  
  ## Changes

  $CHANGES

include-labels:
  - 'type: feat'
  - 'type: fix'
  - 'type: docs'
  - 'type: refactor'
  - 'type: test'
  - 'type: chore'
  - 'type: ci'
  - 'feature'
  - 'bug'
  - 'breaking'
  - 'breaking-change'

exclude-labels:
  - 'skip-changelog'
  - 'internal'

prerelease-identifier: 'alpha'
commitish: 'main'
