global using AutoFixture;
global using AwesomeAssertions;
global using AwsLambda.Host;
global using AwsLambda.Host.Builder;
global using AwsLambda.Host.Core;
global using AwsLambda.Host.Options;
global using JetBrains.Annotations;
global using NSubstitute;
global using Xunit;
