title: ❓ Q&A
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      placeholder: Be specific so others can help you quickly
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Library version (if applicable)
      placeholder: e.g., 1.2.0 or main branch
