//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "24NtoO22UPa+/C0ogM3RV+EAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<string, global::IService>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = string, Name = input, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<string>();
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                castHandler.Invoke(arg0, arg1);
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "24NtoO22UPa+/C0ogM3RV9AAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(8,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            builder.Services.AddSingleton<IFeatureProvider, DefaultEventFeatureProvider<string>>();
            return builder.Build();
        }
    }
}
