//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(8,8)
        [InterceptsLocation(1, "SBl4e782DgMu+0FLfrzfUbUAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<string, string>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = string, Name = input, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<string>();
                var response = castHandler.Invoke(arg0);
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<string> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'string' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "SBl4e782DgMu+0FLfrzfUaQAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(6,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            builder.Services.AddSingleton<IFeatureProvider, DefaultEventFeatureProvider<string>>();
            builder.Services.AddSingleton<IFeatureProvider, DefaultResponseFeatureProvider<string>>();
            return builder.Build();
        }
    }
}
