//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(9,8)
        [InterceptsLocation(1, "52YQ/UddFuGQH5asNzsp/L0AAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::System.Threading.Tasks.Task<string>>)handler;

            return application.Handle(InvocationDelegate);

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                var response = await castHandler.Invoke();
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<string> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'string' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
            }
        }
        
        [InterceptsLocation(1, "52YQ/UddFuGQH5asNzsp/KwAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(7,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            builder.Services.AddSingleton<IFeatureProvider, DefaultResponseFeatureProvider<string>>();
            return builder.Build();
        }
    }
}
