//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(8,8)
        [InterceptsLocation(1, "y3YjupFy8zlpGiubrrDYOrAAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<string, global::IService, global::IService>)handler;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = string, Name = input, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetEventT<string>();
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                context.Response = castHandler.Invoke(arg0, arg1);
                return Task.CompletedTask; 
            }
            
            Task Deserializer(ILambdaHostContext context, ILambdaSerializer serializer, Stream eventStream)
            {
                context.Event = serializer.Deserialize<string>(eventStream);
                return Task.CompletedTask;
            }
            
            Task<Stream> Serializer(ILambdaHostContext context, ILambdaSerializer serializer)
            {
                var response = context.GetResponseT<global::IService>();
                var outputStream = new MemoryStream();
                outputStream.SetLength(0L);
                serializer.Serialize<global::IService>(response, outputStream);
                outputStream.Position = 0L;
                return Task.FromResult<Stream>(outputStream);
            }

            return application.MapHandler(InvocationDelegate, Deserializer, Serializer);
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
