//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "6HO/UYhbMUo2aMF5OFFj3scAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::System.IO.Stream>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                var response = castHandler.Invoke();
                context.RawInvocationData.Response = response;
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "6HO/UYhbMUo2aMF5OFFj3rYAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(8,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            return builder.Build();
        }
    }
}
