//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(13,8)
        [InterceptsLocation(1, "tcgIkMWvnCYF2LFqsYCnnR8BAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<string, global::Amazon.Lambda.Core.ILambdaContext, global::System.Threading.CancellationToken, global::IService, global::IService?, global::IService, global::IService?>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = string, Name = request, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetEventT<string>();
                // ParameterInfo { Type = global::Amazon.Lambda.Core.ILambdaContext, Name = context, Source = Context, IsNullable = False, IsOptional = False}
                var arg1 = context;
                // ParameterInfo { Type = global::System.Threading.CancellationToken, Name = cancellationToken, Source = CancellationToken, IsNullable = False, IsOptional = False}
                var arg2 = context.CancellationToken;
                // ParameterInfo { Type = global::IService, Name = service0, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key0", Type = string, BaseType = object } }
                var arg3 = context.ServiceProvider.GetRequiredKeyedService<global::IService>("key0");
                // ParameterInfo { Type = global::IService?, Name = service1, Source = KeyedService, IsNullable = True, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key1", Type = string, BaseType = object } }
                var arg4 = context.ServiceProvider.GetKeyedService<global::IService?>("key1");
                // ParameterInfo { Type = global::IService, Name = service2, Source = Service, IsNullable = False, IsOptional = False}
                var arg5 = context.ServiceProvider.GetRequiredService<global::IService>();
                // ParameterInfo { Type = global::IService?, Name = service3, Source = Service, IsNullable = True, IsOptional = False}
                var arg6 = context.ServiceProvider.GetService<global::IService?>();
                castHandler.Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "tcgIkMWvnCYF2LFqsYCnneQAAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(9,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            builder.Services.AddSingleton<IFeatureProvider, EventFeatureProvider>();
            return builder.Build();
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static void SetResponseT<T>(this ILambdaHostContext context, T response)
        {
            if (response is Stream stream)
            {
                context.RawInvocationData.Response = stream;
                return;
            }
    
            if (!context.Features.TryGet<IResponseFeature>(out var responseFeature))
            {
                throw new InvalidOperationException("Response feature is not available in the context.");
            }
    
            responseFeature.SetResponse(response);
        }
    }
    
    file class EventFeatureProvider(ILambdaSerializer lambdaSerializer) : IFeatureProvider
    {
        private static readonly Type FeatureType = typeof(IEventFeature);
    
        public bool TryCreate(Type type, out object? feature)
        {
            feature = type == FeatureType ? new EventFeature(lambdaSerializer) : null;
    
            return feature is not null;
        }
    }    
    
    file class EventFeature : IEventFeature
    {
#nullable disable    
        private string _data;
#nullable restore
    
        private readonly ILambdaSerializer _lambdaSerializer;
    
        public EventFeature(ILambdaSerializer lambdaSerializer)
        {
            ArgumentNullException.ThrowIfNull(lambdaSerializer);
    
            _lambdaSerializer = lambdaSerializer;
        }
    
        public object? GetEvent(ILambdaHostContext context)
        {
            _data ??= _lambdaSerializer.Deserialize<string>(context.RawInvocationData.Event);
    
            return _data;
        }
    }
}
