//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(8,8)
        [InterceptsLocation(1, "d/b8S4JZvGJ0B/hzlP8l4ZMAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action)handler;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                castHandler.Invoke();
            }
            
            Task Deserializer(ILambdaHostContext context, ILambdaSerializer serializer, Stream eventStream)
            {
                return Task.CompletedTask;
            }
            
            Task<Stream> Serializer(ILambdaHostContext context, ILambdaSerializer serializer)
            {
                return Task.FromResult<Stream>(new MemoryStream(0));
            }

            return application.Map(InvocationDelegate, Deserializer, Serializer);
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
