//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;
 
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]   
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";
    
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "YAIayk0naS2HI+NqiUzlmO0AAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::CustomRequest, global::IService, global::Amazon.Lambda.Core.ILambdaContext, global::System.Threading.Tasks.Task<global::CustomResponse>>)handler;
            
            application.Handle(InvocationDelegate);
            
            if (!application.Properties.ContainsKey(EventFeatureProviderKey))
                application.Properties[EventFeatureProviderKey] = application
                    .Services.GetRequiredService<IEventFeatureProviderFactory>()
                    .Create<global::CustomRequest>();
            
            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application.
                    Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<global::CustomResponse>();
            
            return application;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = global::CustomRequest, Name = request, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<global::CustomRequest>();
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                // ParameterInfo { Type = global::Amazon.Lambda.Core.ILambdaContext, Name = context, Source = Context, IsNullable = False, IsOptional = False}
                var arg2 = context;
                var response = await castHandler.Invoke(arg0, arg1, arg2);
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<global::CustomResponse> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'global::CustomResponse' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
            }
        }
    }
}
