//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;
 
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]   
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]
    file static class MapHandlerLambdaApplicationExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";
    
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "wn/8VnbL6/5enHoptgINB+cAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::System.Threading.CancellationToken, global::Amazon.Lambda.Core.ILambdaContext, string>)handler;
            
            application.Handle(InvocationDelegate);
            
            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application.
                    Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<string>();
            
            return application;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = global::System.Threading.CancellationToken, Name = ct, Source = CancellationToken, IsNullable = False, IsOptional = False}
                var arg0 = context.CancellationToken;
                // ParameterInfo { Type = global::Amazon.Lambda.Core.ILambdaContext, Name = ctx, Source = Context, IsNullable = False, IsOptional = False}
                var arg1 = context;
                var response = castHandler.Invoke(arg0, arg1);
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<string> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'string' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
                return Task.CompletedTask; 
            }
        }
    }
}
