//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Options;

    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(13,8)
        [InterceptsLocation(1, "K45JpkyREytWedvA3UBOZ0UBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Request>, global::IService, global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Response>>)handler;
            var settings = application.Services.GetRequiredService<IOptions<LambdaHostOptions>>().Value;
            global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Request>.RegisterConverter(settings.JsonSerializerOptions.Converters);
            global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Response>.RegisterConverter(settings.JsonSerializerOptions.Converters);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Request>, Name = request, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetEventT<global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Request>>();
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                context.Response = castHandler.Invoke(arg0, arg1);
                return Task.CompletedTask; 
            }
            
            Task Deserializer(ILambdaHostContext context, ILambdaSerializer serializer, Stream eventStream)
            {
                context.Event = serializer.Deserialize<global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Request>>(eventStream);
                return Task.CompletedTask;
            }
            
            Task<Stream> Serializer(ILambdaHostContext context, ILambdaSerializer serializer)
            {
                var response = context.GetResponseT<global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Response>>();
                var outputStream = new MemoryStream();
                outputStream.SetLength(0L);
                serializer.Serialize<global::AwsLambda.Host.Envelopes.APIGateway.ApiGatewayResponseEnvelope<global::Response>>(response, outputStream);
                outputStream.Position = 0L;
                return Task.FromResult<Stream>(outputStream);
            }

            return application.MapHandler(InvocationDelegate, Deserializer, Serializer);
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
