//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using AwsLambda.Host.Builder;
    using AwsLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(13,8)
        [InterceptsLocation(1, "3eiN2asEW2/G+R1Aj4dbcqIBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<global::IService, global::IService, global::IService>)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = global::IService, Name = serviceA, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (uint)42, Type = uint, BaseType = global::System.ValueType } }
                var arg0 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((uint)42);
                // ParameterInfo { Type = global::IService, Name = serviceB, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (ulong)42, Type = ulong, BaseType = global::System.ValueType } }
                var arg1 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((ulong)42);
                // ParameterInfo { Type = global::IService, Name = serviceC, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (ushort)42, Type = ushort, BaseType = global::System.ValueType } }
                var arg2 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((ushort)42);
                castHandler.Invoke(arg0, arg1, arg2);
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "3eiN2asEW2/G+R1Aj4dbcpEBAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(11,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            return builder.Build();
        }
    }
}
