//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "u3QMKmsaQkO2Z61JJGU4FjoBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<global::IService, global::IService>)handler;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = global::IService, Name = serviceA, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (int)42, Type = int, BaseType = global::System.ValueType } }
                var arg0 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((int)42);
                // ParameterInfo { Type = global::IService, Name = serviceB, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (long)42, Type = long, BaseType = global::System.ValueType } }
                var arg1 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((long)42);
                castHandler.Invoke(arg0, arg1);
                return Task.CompletedTask; 
            }
            
            Task Deserializer(ILambdaHostContext context, ILambdaSerializer serializer, Stream eventStream)
            {
                return Task.CompletedTask;
            }
            
            Task<Stream> Serializer(ILambdaHostContext context, ILambdaSerializer serializer)
            {
                return Task.FromResult<Stream>(new MemoryStream(0));
            }

            return application.Map(InvocationDelegate, Deserializer, Serializer);
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
