//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(13,8)
        [InterceptsLocation(1, "IsM4FA3W7thmbE0DtjQI1sEBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<global::IService, global::IService, global::IService, global::IService>)handler;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = global::IService, Name = serviceA, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = true, Type = bool, BaseType = global::System.ValueType } }
                var arg0 = context.ServiceProvider.GetRequiredKeyedService<global::IService>(true);
                // ParameterInfo { Type = global::IService, Name = serviceB, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = 'A', Type = char, BaseType = global::System.ValueType } }
                var arg1 = context.ServiceProvider.GetRequiredKeyedService<global::IService>('A');
                // ParameterInfo { Type = global::IService, Name = serviceC, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = typeof(global::Service), Type = global::System.Type, BaseType = global::System.Reflection.MemberInfo } }
                var arg2 = context.ServiceProvider.GetRequiredKeyedService<global::IService>(typeof(global::Service));
                // ParameterInfo { Type = global::IService, Name = serviceD, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = null, Type = object, BaseType =  } }
                var arg3 = context.ServiceProvider.GetRequiredKeyedService<global::IService>(null);
                castHandler.Invoke(arg0, arg1, arg2, arg3);
                return Task.CompletedTask; 
            }
            
            Task Deserializer(ILambdaHostContext context, ILambdaSerializer serializer, Stream eventStream)
            {
                return Task.CompletedTask;
            }
            
            Task<Stream> Serializer(ILambdaHostContext context, ILambdaSerializer serializer)
            {
                return Task.FromResult<Stream>(new MemoryStream(0));
            }

            return application.Map(InvocationDelegate, Deserializer, Serializer);
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
