//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "IqMG6GXKYzwtohgR+tzVZ90AAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<string, global::Amazon.Lambda.Core.ILambdaContext, global::IService, string>)handler;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = string, Name = input, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetEventT<string>();
                // ParameterInfo { Type = global::Amazon.Lambda.Core.ILambdaContext, Name = context, Source = Context, IsNullable = False, IsOptional = False}
                var arg1 = context;
                // ParameterInfo { Type = global::IService, Name = service, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key", Type = string, BaseType = object } }
                var arg2 = context.ServiceProvider.GetRequiredKeyedService<global::IService>("key");
                context.Response = castHandler.Invoke(arg0, arg1, arg2);
                return Task.CompletedTask; 
            }
            
            Task Deserializer(ILambdaHostContext context, ILambdaSerializer serializer, Stream eventStream)
            {
                context.Event = serializer.Deserialize<string>(eventStream);
                return Task.CompletedTask;
            }
            
            Task<Stream> Serializer(ILambdaHostContext context, ILambdaSerializer serializer)
            {
                var response = context.GetResponseT<string>();
                var outputStream = new MemoryStream();
                outputStream.SetLength(0L);
                serializer.Serialize<string>(response, outputStream);
                outputStream.Position = 0L;
                return Task.FromResult<Stream>(outputStream);
            }

            return application.Map(InvocationDelegate, Deserializer, Serializer);
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
