//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Microsoft.Extensions.DependencyInjection;

    file static class MapHandlerLambdaApplicationExtensions
    {
        // Location: InputFile.cs(8,8)
        [InterceptsLocation(1, "2kHnHtB1ASGReh74fzi0UqAAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action)handler;

            return application.Handle(InvocationDelegate);

            Task InvocationDelegate(ILambdaHostContext context)
            {
                castHandler.Invoke();
                return Task.CompletedTask; 
            }
        }
        
        [InterceptsLocation(1, "2kHnHtB1ASGReh74fzi0Uo8AAABJbnB1dEZpbGUuY3M=")] // Location: InputFile.cs(6,22)
        internal static LambdaApplication BuildInterceptor(this LambdaApplicationBuilder builder)
        {
            return builder.Build();
        }

        private static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        private static void SetResponseT<T>(this ILambdaHostContext context, T response)
        {
            if (response is Stream stream)
            {
                context.RawInvocationData.Response = stream;
                return;
            }
    
            if (!context.Features.TryGet<IResponseFeature>(out var responseFeature))
            {
                throw new InvalidOperationException("Response feature is not available in the context.");
            }
    
            responseFeature.SetResponse(response);
        }
    }
}
