//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;
 
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]   
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using AwsLambda.Host.Builder;
    
    [GeneratedCode("AwsLambda.Host.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaOnInitBuilderExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "kxwv6MRO7ICWs0/b3FHQYdQAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnInitBuilder OnInitInterceptor0(
            this ILambdaOnInitBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::IService, global::System.Threading.Tasks.Task<bool>>)handler;
            
            return application.OnInit(OnInit);
            
            Task<bool> OnInit(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg0 = serviceProvider.GetRequiredService<global::IService>();
                var response = castHandler.Invoke(arg0);
                return response;
            }
        }
    }
}