//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class OnInitLambdaApplicationExtensions
    {
        // Location: InputFile.cs(9,8)
        [InterceptsLocation(1, "Ej4qfMQ3p82acFQPcjI1A7EAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnInitInterceptor0(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::System.Threading.Tasks.Task<bool>>)handler;
            
            return application.OnInit(OnInit);
            
            Task<bool> OnInit(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                var response = castHandler.Invoke();
                return response;
            }
        }
    }
}