//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class OnShutdownLambdaApplicationExtensions
    {
        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "AQrJxIlrC5Au0bNAiyl5s/kAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnShutdownInterceptor0(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::System.Threading.CancellationToken, global::IService, global::IService?, global::IService, global::IService?, global::System.Threading.Tasks.Task>)handler;
            
            return application.OnShutdown(OnShutdown);
            
            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                if (serviceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = global::System.Threading.CancellationToken, Name = token, Source = CancellationToken, IsNullable = False, IsOptional = False}
                var arg0 = cancellationToken;
                // ParameterInfo { Type = global::IService, Name = service1, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key1", Type = string, BaseType = object } }
                var arg1 = serviceProvider.GetRequiredKeyedService<global::IService>("key1");
                // ParameterInfo { Type = global::IService?, Name = service2, Source = KeyedService, IsNullable = True, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key2", Type = string, BaseType = object } }
                var arg2 = serviceProvider.GetKeyedService<global::IService?>("key2");
                // ParameterInfo { Type = global::IService, Name = service3, Source = Service, IsNullable = False, IsOptional = False}
                var arg3 = serviceProvider.GetRequiredService<global::IService>();
                // ParameterInfo { Type = global::IService?, Name = service4, Source = Service, IsNullable = True, IsOptional = False}
                var arg4 = serviceProvider.GetService<global::IService?>();
                var response = castHandler.Invoke(arg0, arg1, arg2, arg3, arg4);
                return response;
            }
        }
    }
}