//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class OnShutdownLambdaApplicationExtensions
    {
        // Location: InputFile.cs(9,8)
        [InterceptsLocation(1, "jcqGO6TqL6PdUwUOchIk46EAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnShutdownInterceptor0(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action)handler;
            
            return application.OnShutdown(OnShutdown);
            
            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                castHandler.Invoke();
                return Task.CompletedTask;
            }
        }
    }
}