//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class LambdaHostOnShutdownExtensions
    {
        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "AQrJxIlrC5Au0bNAiyl5s/kAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnShutdownInterceptor0<T1, T2, T3, T4, T5>(
            this ILambdaApplication application,
            Func<T1, T2, T3, T4, T5, Task> handler
        )
        {
            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                if (serviceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
#pragma warning disable CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
                // ParameterInfo { Type = global::System.Threading.CancellationToken, Name = token, Source = CancellationToken, IsNullable = False, IsOptional = False}
                var arg0 = Unsafe.As<CancellationToken, T1>(ref cancellationToken);
                // ParameterInfo { Type = global::IService, Name = service1, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key1", Type = string, BaseType = object } }
                var arg1 = serviceProvider.GetRequiredKeyedService<T2>("key1");
                // ParameterInfo { Type = global::IService?, Name = service2, Source = KeyedService, IsNullable = True, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key2", Type = string, BaseType = object } }
                var arg2 = serviceProvider.GetKeyedService<T3>("key2");
                // ParameterInfo { Type = global::IService, Name = service3, Source = Service, IsNullable = False, IsOptional = False}
                var arg3 = serviceProvider.GetRequiredService<T4>();
                // ParameterInfo { Type = global::IService?, Name = service4, Source = Service, IsNullable = True, IsOptional = False}
                var arg4 = serviceProvider.GetService<T5>();
#pragma warning restore CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
#pragma warning disable CS8604 // Possible null reference argument.
                return handler(arg0, arg1, arg2, arg3, arg4);
#pragma warning restore CS8604 // Possible null reference argument.
            }
            
            return application.OnShutdown(OnShutdown);
        }
    }
}