//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    
    file static class LambdaHostOnShutdownExtensions
    {
        // Location: InputFile.cs(9,8)
        [InterceptsLocation(1, "752jWHLpcl0NwGol0bVk/LEAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnShutdownInterceptor0(
            this ILambdaApplication application,
            Func<Task> handler
        )
        {
            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                return handler();
            }
            
            return application.OnShutdown(OnShutdown);
        }
        
        // Location: InputFile.cs(14,8)
        [InterceptsLocation(1, "752jWHLpcl0NwGol0bVk/PQAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnShutdownInterceptor1<T1, T2>(
            this ILambdaApplication application,
            Func<T1, T2, Task> handler
        )
        {
            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
#pragma warning disable CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
                var arg0 = serviceProvider.GetService<T1>();
                var arg1 = serviceProvider.GetService<T2>();
#pragma warning restore CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
#pragma warning disable CS8604 // Possible null reference argument.
                return handler(arg0, arg1);
#pragma warning restore CS8604 // Possible null reference argument.
            }
            
            return application.OnShutdown(OnShutdown);
        }
        
        // Location: InputFile.cs(21,8)
        [InterceptsLocation(1, "752jWHLpcl0NwGol0bVk/F8BAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication OnShutdownInterceptor2<T1, T2>(
            this ILambdaApplication application,
            Func<T1, T2, Task> handler
        )
        {
            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
#pragma warning disable CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
                var arg0 = serviceProvider.GetRequiredService<T1>();
                var arg1 = serviceProvider.GetRequiredService<T2>();
#pragma warning restore CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
#pragma warning disable CS8604 // Possible null reference argument.
                return handler(arg0, arg1);
#pragma warning restore CS8604 // Possible null reference argument.
            }
            
            return application.OnShutdown(OnShutdown);
        }
    }
}