//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "pFmNilf4Mnn4w37D3X60uS4BAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::CustomRequest, global::IService, global::Amazon.Lambda.Core.ILambdaContext, global::System.Threading.Tasks.Task<global::CustomResponse>>)handler;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                var arg0 = context.GetEventT<global::CustomRequest>();
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                var arg2 = context;
                context.Response = await castHandler.Invoke(arg0, arg1, arg2);
            }
            
            void Deserializer(ILambdaHostContext context, Stream eventStream)
            {
                context.Event = context.LambdaSerializer.Deserialize<global::CustomRequest>(eventStream);
            }
            
            Stream Serializer(ILambdaHostContext context)
            {
                var response = context.GetResponseT<global::CustomResponse>();
                var outputStream = new MemoryStream();
                outputStream.SetLength(0L);
                context.LambdaSerializer.Serialize<global::CustomResponse>(response, outputStream);
                outputStream.Position = 0L;
                return outputStream;
            }

            return application.MapHandler(InvocationDelegate, Deserializer, Serializer);
        }
    }
    
    file static class HelperExtensions
    {
        public static T GetEventT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetEvent<T>(out var eventT))
            {
                throw new InvalidOperationException($"Lambda event of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return eventT!;
        }

        public static T GetResponseT<T>(this ILambdaHostContext context)
        {
            if (!context.TryGetResponse<T>(out var responseT))
            {
                throw new InvalidOperationException($"Lambda response of type '{typeof(T).FullName}' is not available in the context.");
            }
            
            return responseT!;
        }
    }
}
