//HintName: LambdaStartup.g.cs
// <auto-generated>
//     Generated by the Lambda.Host source generator.
// </auto-generated>

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace Tests;

public class LambdaStartupService : global::Microsoft.Extensions.Hosting.IHostedService
{
    private readonly global::Lambda.Host.DelegateHolder _delegateHolder;
    private readonly global::System.IServiceProvider _serviceProvider;

    public LambdaStartupService(global::Lambda.Host.DelegateHolder delegateHolder, global::System.IServiceProvider serviceProvider)
    {
        this._delegateHolder = delegateHolder;
        this._serviceProvider = serviceProvider;
    }
    
    public async global::System.Threading.Tasks.Task StartAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        if (!this._delegateHolder.IsHandlerSet)
            throw new global::System.InvalidOperationException("Handler is not set");
            
        if (this._delegateHolder.Handler is not global::System.Action<global::System.IO.Stream> lambdaHandler)
            throw new global::System.InvalidOperationException("Invalid handler type.");
            
        await global::Amazon.Lambda.RuntimeSupport.LambdaBootstrapBuilder
            .Create(
                (global::System.IO.Stream input) => 
                {
                    using var __scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(this._serviceProvider);
                    
                    lambdaHandler(input);
                }
            )
            .Build()
            .RunAsync(cancellationToken);
    }

    public global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        return global::System.Threading.Tasks.Task.CompletedTask;
    }
}