//HintName: LambdaStartup.g.cs
// <auto-generated>
//     Generated by the Lambda.Host source generator.
// </auto-generated>

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace Tests;

public class LambdaApplication : global::Lambda.Host.LambdaHostedService
{
    public LambdaApplication(
        global::Microsoft.Extensions.Options.IOptions<global::Lambda.Host.LambdaHostSettings> lambdaHostSettings,
        global::Lambda.Host.DelegateHolder delegateHolder,
        global::System.IServiceProvider serviceProvider,
        global::Lambda.Host.Interfaces.ILambdaCancellationTokenSourceFactory lambdaCancellationTokenSourceFactory
    )
        : base(
            lambdaHostSettings,
            delegateHolder,
            serviceProvider,
            lambdaCancellationTokenSourceFactory
        ) { }
    
    public override global::System.Threading.Tasks.Task StartAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        if (!this.DelegateHolder.IsHandlerSet)
            throw new global::System.InvalidOperationException("Handler is not set");
            
        if (this.DelegateHolder.Handler is not global::System.Func<global::System.Threading.CancellationToken, string> lambdaHandler)
            throw new global::System.InvalidOperationException("Invalid handler type.");
            
        global::Amazon.Lambda.RuntimeSupport.LambdaBootstrapBuilder
            .Create(
                (global::Amazon.Lambda.Core.ILambdaContext lambdaContext) => 
                {
                    using var __cancellationTokenSource = this.LambdaCancellationTokenSourceFactory.NewCancellationTokenSource(lambdaContext);
                    var cancellationToken = __cancellationTokenSource.Token;
                    
                    var __response = lambdaHandler(cancellationToken);
                    
                    return __response;
                },
                this.LambdaHostSettings.LambdaSerializer
            )
            .Build()
            .RunAsync(cancellationToken);
        
        return global::System.Threading.Tasks.Task.CompletedTask;
    }
}