//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace Lambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(8,8)
        [InterceptsLocation(1, "s/LSD/WSHXWeHQ+GMomHapAAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action)handler;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                castHandler.Invoke();
            }
            
            void Deserializer(ILambdaHostContext context, Stream eventStream)
            {
            }
            
            Stream Serializer(ILambdaHostContext context)
            {
                // No response, return empty stream.
                return new MemoryStream(0);
            }

            return application.MapHandler(InvocationDelegate, Deserializer, Serializer);
        }
    }
}
