//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace Lambda.Host
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;

    file static class LambdaHostMapHandlerExtensions
    {
        // Location: InputFile.cs(12,8)
        [InterceptsLocation(1, "XOSB2a0eqz5HW6z9alxW1yUBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaApplication MapHandlerInterceptor(
            this ILambdaApplication application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::MyNamespace.Event, global::IService, global::System.Threading.Tasks.Task<global::MyNamespace.Response>>)handler;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                var arg0 = context.GetEvent<global::MyNamespace.Event>() ?? throw new InvalidOperationException($"Lambda event of type '{typeof(global::MyNamespace.Event).FullName}' is not available in the context.");
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                context.Response = await castHandler.Invoke(arg0, arg1);
            }
            
            void Deserializer(ILambdaHostContext context, Stream eventStream)
            {
                context.Event = context.LambdaSerializer.Deserialize<global::MyNamespace.Event>(eventStream);
            }
            
            Stream Serializer(ILambdaHostContext context)
            {
                // Creating a new stream and serializing the response to it.
                var response = context.GetResponse<global::MyNamespace.Response>() ?? throw new InvalidOperationException($"Lambda response of type '{typeof(global::MyNamespace.Response).FullName}' is not available in the context.");
                var outputStream = new MemoryStream();
                outputStream.SetLength(0L);
                context.LambdaSerializer.Serialize<global::MyNamespace.Response>(response, outputStream);
                outputStream.Position = 0L;
                return outputStream;
            }

            return application.MapHandler(InvocationDelegate, Deserializer, Serializer);
        }
    }
}
