//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        [InterceptsLocation(1, "RRgc5MNn+AL4pWTKQhrXsLYAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task<string> () => throw null!);

            application.Handle(InvocationDelegate);

            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application.
                    Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<string>();

            return application;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                var response = await castHandler.Invoke();
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<string> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'string' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}