//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using MinimalLambda.Host.Builder;
    using MinimalLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        // Location: InputFile.cs(14,8)
        [InterceptsLocation(1, "wCxh64raLv7JZxUcekz6bkIBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Action<string, global::Amazon.Lambda.Core.ILambdaContext, global::System.Threading.CancellationToken, global::IService, global::IService?, global::IService, global::IService?>)handler;

            application.Handle(InvocationDelegate);

            if (!application.Properties.ContainsKey(EventFeatureProviderKey))
                application.Properties[EventFeatureProviderKey] = application
                    .Services.GetRequiredService<IEventFeatureProviderFactory>()
                    .Create<string>();

            return application;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = string, Name = request, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<string>();
                // ParameterInfo { Type = global::Amazon.Lambda.Core.ILambdaContext, Name = context, Source = Context, IsNullable = False, IsOptional = False}
                var arg1 = context;
                // ParameterInfo { Type = global::System.Threading.CancellationToken, Name = cancellationToken, Source = CancellationToken, IsNullable = False, IsOptional = False}
                var arg2 = context.CancellationToken;
                // ParameterInfo { Type = global::IService, Name = service0, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key0", Type = string, BaseType = object } }
                var arg3 = context.ServiceProvider.GetRequiredKeyedService<global::IService>("key0");
                // ParameterInfo { Type = global::IService?, Name = service1, Source = KeyedService, IsNullable = True, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = "key1", Type = string, BaseType = object } }
                var arg4 = context.ServiceProvider.GetKeyedService<global::IService?>("key1");
                // ParameterInfo { Type = global::IService, Name = service2, Source = Service, IsNullable = False, IsOptional = False}
                var arg5 = context.ServiceProvider.GetRequiredService<global::IService>();
                // ParameterInfo { Type = global::IService?, Name = service3, Source = Service, IsNullable = True, IsOptional = False}
                var arg6 = context.ServiceProvider.GetService<global::IService?>();
                castHandler.Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return Task.CompletedTask;
            }
        }
    }
}
