//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::IService (string arg0, global::IService arg1) => throw null!);

            application.Handle(InvocationDelegate);

            if (!application.Properties.ContainsKey(EventFeatureProviderKey))
                application.Properties[EventFeatureProviderKey] = application
                    .Services.GetRequiredService<IEventFeatureProviderFactory>()
                    .Create<string>();

            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application.
                    Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<global::IService>();

            return application;

            Task InvocationDelegate(ILambdaInvocationContext context)
            {
                // ParameterInfo { Type = string, Name = input, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<string>();
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                var response = castHandler.Invoke(arg0, arg1);
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<global::IService> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'global::IService' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
                return Task.CompletedTask;
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}