//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using MinimalLambda.Builder;
    using MinimalLambda;
    using Microsoft.Extensions.DependencyInjection;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        // Location: InputFile.cs(11,8)
        [InterceptsLocation(1, "2v0Mx0/EAUlNqfkx9U5JLucAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::MyNamespace.Event, global::IService, global::System.Threading.Tasks.Task<global::MyNamespace.Response>>)handler;

            application.Handle(InvocationDelegate);

            if (!application.Properties.ContainsKey(EventFeatureProviderKey))
                application.Properties[EventFeatureProviderKey] = application
                    .Services.GetRequiredService<IEventFeatureProviderFactory>()
                    .Create<global::MyNamespace.Event>();

            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application.
                    Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<global::MyNamespace.Response>();

            return application;

            async Task InvocationDelegate(ILambdaHostContext context)
            {
                // ParameterInfo { Type = global::MyNamespace.Event, Name = input, Source = Event, IsNullable = False, IsOptional = False}
                var arg0 = context.GetRequiredEvent<global::MyNamespace.Event>();
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<global::IService>();
                var response = await castHandler.Invoke(arg0, arg1);
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<global::MyNamespace.Response> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'global::MyNamespace.Response' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
            }
        }
    }
}
