//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        [InterceptsLocation(1, "AxgJhn/c6EE+EjInktbZjJsBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, void (global::IService arg0, global::IService arg1, global::IService arg2) => throw null!);

            application.Handle(InvocationDelegate);

            return application;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                // ParameterInfo { Type = global::IService, Name = serviceA, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (uint)42, Type = uint, BaseType = global::System.ValueType } }
                var arg0 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((uint)42);
                // ParameterInfo { Type = global::IService, Name = serviceB, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (ulong)42, Type = ulong, BaseType = global::System.ValueType } }
                var arg1 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((ulong)42);
                // ParameterInfo { Type = global::IService, Name = serviceC, Source = KeyedService, IsNullable = False, IsOptional = False, KeyedServiceKeyInfo { DisplayValue = (ushort)42, Type = ushort, BaseType = global::System.ValueType } }
                var arg2 = context.ServiceProvider.GetRequiredKeyedService<global::IService>((ushort)42);
                castHandler.Invoke(arg0, arg1, arg2);
                return Task.CompletedTask;
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}