//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AwsLambda.Host.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using MinimalLambda.Host.Builder;
    using MinimalLambda.Host.Core;
    using Microsoft.Extensions.DependencyInjection;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        // Location: InputFile.cs(9,8)
        [InterceptsLocation(1, "MYd9JR07N7unKiyCLFng0cMAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaInvocationBuilder MapHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<int>)handler;

            application.Handle(InvocationDelegate);

            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application.
                    Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<int>();

            return application;

            Task InvocationDelegate(ILambdaHostContext context)
            {
                var response = castHandler.Invoke();
                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<int> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type 'int' is not available in the collection.");
                }
                responseFeature.SetResponse(response);
                return Task.CompletedTask;
            }
        }
    }
}
