//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Core.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda.Builder;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaOnInitBuilderExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "0/e3oTWVwerLdIUT9JSUddQAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnInitBuilder OnInitInterceptor0(
            this ILambdaOnInitBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<global::IService, global::System.Threading.Tasks.Task<string>>)handler;

            return application.OnInit(OnInit);

            async Task<bool> OnInit(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg0 = serviceProvider.GetRequiredService<global::IService>();
                await castHandler.Invoke(arg0);
                return true;
            }
        }
    }
}
