//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda.Builder;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaOnInitBuilderExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "pi9PolKCGMrmFvoC3ft/Oc0AAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnInitBuilder OnInitInterceptor0(
            this ILambdaOnInitBuilder application,
            Delegate handler
        )
        {
            var castHandler = Cast(handler, global::System.Threading.Tasks.Task<string> () => throw null!);

            return application.OnInit(OnInit);

            async Task<bool> OnInit(ILambdaLifecycleContext context)
            {
                await castHandler.Invoke();
                return true;
            }
        }
        
        private static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}