//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaOnInitBuilderExtensions
    {
        [InterceptsLocation(1, "gOjUxL7brRqHQuY3oQ1zfc0AAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnInitBuilder OnInitInterceptor0(
            this ILambdaOnInitBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task<bool> () => throw null!);

            return application.OnInit(OnInit);

            Task<bool> OnInit(ILambdaLifecycleContext context)
            {
                var response = castHandler.Invoke();
                return response;
            }
        }
        
        [InterceptsLocation(1, "gOjUxL7brRqHQuY3oQ1zfRUBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnInitBuilder OnInitInterceptor1(
            this ILambdaOnInitBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task<bool> (string? arg0, global::IService? arg1) => throw null!);

            return application.OnInit(OnInit);

            Task<bool> OnInit(ILambdaLifecycleContext context)
            {
                // ParameterInfo { Type = string?, Name = x, Source = Service, IsNullable = True, IsOptional = False}
                var arg0 = context.ServiceProvider.GetService<string?>();
                // ParameterInfo { Type = global::IService?, Name = y, Source = Service, IsNullable = True, IsOptional = False}
                var arg1 = context.ServiceProvider.GetService<global::IService?>();
                var response = castHandler.Invoke(arg0, arg1);
                return response;
            }
        }
        
        [InterceptsLocation(1, "gOjUxL7brRqHQuY3oQ1zfXoBAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnInitBuilder OnInitInterceptor2(
            this ILambdaOnInitBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task<bool> (string arg0, int arg1) => throw null!);

            return application.OnInit(OnInit);

            Task<bool> OnInit(ILambdaLifecycleContext context)
            {
                // ParameterInfo { Type = string, Name = x, Source = Service, IsNullable = False, IsOptional = False}
                var arg0 = context.ServiceProvider.GetRequiredService<string>();
                // ParameterInfo { Type = int, Name = y, Source = Service, IsNullable = False, IsOptional = False}
                var arg1 = context.ServiceProvider.GetRequiredService<int>();
                var response = castHandler.Invoke(arg0, arg1);
                return response;
            }
        }
    }
    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}