//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda.Builder;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    file static class GeneratedLambdaOnShutdownBuilderExtensions
    {
        // Location: InputFile.cs(10,8)
        [InterceptsLocation(1, "UPiaK81+RguBpV3LlTD6qtQAAABJbnB1dEZpbGUuY3M=")]
        internal static ILambdaOnShutdownBuilder OnShutdownInterceptor0(
            this ILambdaOnShutdownBuilder application,
            Delegate handler
        )
        {
            var castHandler = (global::System.Func<string?, global::IService?, global::System.Threading.Tasks.Task>)handler;

            return application.OnShutdown(OnShutdown);

            Task OnShutdown(IServiceProvider serviceProvider, CancellationToken cancellationToken)
            {
                // ParameterInfo { Type = string?, Name = x, Source = Service, IsNullable = True, IsOptional = False}
                var arg0 = serviceProvider.GetService<string?>();
                // ParameterInfo { Type = global::IService?, Name = y, Source = Service, IsNullable = True, IsOptional = False}
                var arg1 = serviceProvider.GetService<global::IService?>();
                var response = castHandler.Invoke(arg0, arg1);
                return response;
            }
        }
    }
}
