//HintName: MinimalLambda.OnShutdownHandlers.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class GeneratedLambdaOnShutdownExtensions
    {
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaOnShutdownBuilder OnShutdownInterceptor0(
            this ILambdaOnShutdownBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task (global::System.Threading.CancellationToken arg0, global::IService arg1, global::IService? arg2, global::IService arg3, global::IService? arg4) => throw null!);

            return application.OnShutdown(OnShutdown);

            Task OnShutdown(ILambdaLifecycleContext context)
            {
                if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                {
                    throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                }
                var arg0 = context.CancellationToken;
                var arg1 = context.ServiceProvider.GetRequiredKeyedService<global::IService>("key1");
                var arg2 = context.ServiceProvider.GetKeyedService<global::IService?>("key2");
                var arg3 = context.ServiceProvider.GetRequiredService<global::IService>();
                var arg4 = context.ServiceProvider.GetService<global::IService?>();
                var response = castHandler.Invoke(arg0, arg1, arg2, arg3, arg4);
                return response;
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}