//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [GeneratedCode("MinimalLambda.SourceGenerators", "0.0.0")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}
