//HintName: MinimalLambda.OnShutdownHandlers.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class GeneratedLambdaOnShutdownExtensions
    {
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaOnShutdownBuilder OnShutdownInterceptor0(
            this ILambdaOnShutdownBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task (string? arg0, global::IService? arg1) => throw null!);

            return application.OnShutdown(OnShutdown);

            Task OnShutdown(ILambdaLifecycleContext context)
            {
                var arg0 = context.ServiceProvider.GetService<string?>();
                var arg1 = context.ServiceProvider.GetService<global::IService?>();
                var response = castHandler.Invoke(arg0, arg1);
                return response;
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}