//HintName: LambdaHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class UseMiddlewareExtensions
    {
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder UseMiddleware0<T>(
            this ILambdaInvocationBuilder builder,
            params object[] args
        )
            where T : ILambdaMiddleware
        {
            var resolver = new MyLambdaMiddlewareResolver0(args);
            
            builder.Use(next =>
            {
                return context =>
                {
                    return resolver.Create(context).InvokeAsync(context, next);
                };
            });

            return builder;
        }

        private class MyLambdaMiddlewareResolver0
        {
            private readonly object[] _args;

            internal MyLambdaMiddlewareResolver0(object[] args) => _args = args;

            internal global::MyLambdaMiddleware Create(ILambdaInvocationContext context)
            {
                // ParameterInfo { Type = global::IService, Name = service, Source = Service, IsNullable = False, IsOptional = False}
                var arg0 = context.ServiceProvider.GetRequiredService<global::IService>();
                
                return new global::MyLambdaMiddleware(arg0);
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}