using Lambda.Host.Interfaces;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace Lambda.Host;

public abstract class LambdaHostedService : IHostedService
{
    protected readonly DelegateHolder DelegateHolder;
    protected readonly ILambdaCancellationTokenSourceFactory LambdaCancellationTokenSourceFactory;
    protected readonly LambdaHostSettings LambdaHostSettings;
    protected readonly IServiceProvider ServiceProvider;

    protected LambdaHostedService(
        IOptions<LambdaHostSettings> lambdaHostSettings,
        DelegateHolder delegateHolder,
        IServiceProvider serviceProvider,
        ILambdaCancellationTokenSourceFactory lambdaCancellationTokenSourceFactory
    )
    {
        LambdaHostSettings =
            lambdaHostSettings.Value ?? throw new ArgumentNullException(nameof(lambdaHostSettings));
        DelegateHolder = delegateHolder ?? throw new ArgumentNullException(nameof(delegateHolder));
        ServiceProvider =
            serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        LambdaCancellationTokenSourceFactory =
            lambdaCancellationTokenSourceFactory
            ?? throw new ArgumentNullException(nameof(lambdaCancellationTokenSourceFactory));
    }

    public virtual Task StartAsync(CancellationToken cancellationToken) =>
        throw new NotImplementedException(
            "StartAsync has not been generated by the Lambda.Host.SourceGenerators package."
        );

    public virtual Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
